# fly.toml app configuration file generated for passprotectorpro-green-bush-61 on 2024-05-23T10:55:20+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'passprotectorpro-green-bush-61'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
